# Generated by Django 5.2.7 on 2026-08-12 05:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_use_supabase_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffFeatureGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(choices=[('ingredients_manage', 'Manage Ingredients'), ('menus_manage', 'Manage Menus'), ('profit_analytics', 'Profit Analytics'), ('brief', 'Daily Brief')], max_length=50)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('staff', 'feature')},
            },
        ),
    ]
