# Generated by Django 6.1 on 2026-08-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_business_username'),
        ('accounts', '0003_stafffeaturegrant'),
    ]

    operations = [
    ]
