# Generated by Django 5.2.7 on 2026-08-12 18:01

import django.core.validators
from django.db import migrations, models


def backfill_zero_target_margin(apps, schema_editor):
    """Existing menus were created back when target_margin defaulted to 0,
    which made every menu classify as 'high' regardless of real margin
    (B3). Bump those to the new default so old menus get real
    classification too, not just menus created from now on."""
    Menu = apps.get_model('menus', 'Menu')
    Menu.objects.filter(target_margin=0).update(target_margin=30)


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_menu_sell_price_alter_menu_target_margin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='target_margin',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RunPython(backfill_zero_target_margin, migrations.RunPython.noop),
    ]
