# Generated by Django 6.1 on 2026-08-12 18:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_menu_sell_price_alter_menu_target_margin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='target_margin',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
