# Generated by Django 6.1 on 2026-08-12 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_alter_menu_sell_price_alter_menu_target_margin'),
        ('menus', '0004_alter_menu_target_margin'),
    ]

    operations = [
    ]
