# Generated by Django 6.1 on 2026-08-12 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_ingredient_cost_per_unit_and_more'),
        ('menus', '0005_merge_20260813_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='active_discount_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='active_discount_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.ingredient'),
        ),
        migrations.AddField(
            model_name='menu',
            name='active_discount_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
