# Generated by Django 6.1 on 2026-08-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_menu_active_discount_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='manual_discount_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='manual_discount_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
