# Generated by Django 5.2.7 on 2026-08-13 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_menu_manual_discount_pct_menu_manual_discount_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='active_discount_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='manual_discount_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
