# Generated by Django 6.1 on 2026-08-11 05:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('low_stock_threshold', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='accounts.business')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('movement_type', models.CharField(choices=[('restock', 'Restock'), ('adjustment', 'Adjustment'), ('sale_deduction', 'Sale deduction')], max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.ingredient')),
            ],
        ),
    ]
