# Generated by Django 5.2.7 on 2026-08-12 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_fix_created_by_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='current_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='low_stock_threshold',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
