# Generated by Django 6.1 on 2026-08-11 05:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BriefAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('restock', 'Restock'), ('discount', 'Discount'), ('review_menu', 'Review menu'), ('expiry_alert', 'Expiry alert')], max_length=20)),
                ('message', models.TextField()),
                ('rupiah_impact', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acted', 'Acted'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DailyBrief',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brief_date', models.DateField()),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
