# Generated by Django 6.1 on 2026-08-11 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('briefs', '0001_initial'),
        ('inventory', '0001_initial'),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefaction',
            name='related_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.ingredient'),
        ),
        migrations.AddField(
            model_name='briefaction',
            name='related_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.menu'),
        ),
        migrations.AddField(
            model_name='dailybrief',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefs', to='accounts.business'),
        ),
        migrations.AddField(
            model_name='briefaction',
            name='brief',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='briefs.dailybrief'),
        ),
        migrations.AlterUniqueTogether(
            name='dailybrief',
            unique_together={('business', 'brief_date')},
        ),
    ]
