# Generated by Django 6.1 on 2026-08-12 05:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0003_use_supabase_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefaction',
            name='acted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='briefaction',
            name='baseline_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ActionImpactCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField()),
                ('followup_snapshot', models.JSONField()),
                ('answer', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('inconclusive', 'Inconclusive'), ('external', 'Likely external')], max_length=15)),
                ('reasoning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_checks', to='briefs.briefaction')),
            ],
            options={
                'db_table': 'action_impact_check',
                'ordering': ['-week_start'],
                'unique_together': {('action', 'week_start')},
            },
        ),
    ]
