# Generated by Django 5.2.7 on 2026-08-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0004_briefaction_acted_at_briefaction_baseline_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actionimpactcheck',
            table='action_impact_checks',
        ),
    ]
