# Generated by Django 6.1 on 2026-08-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0005_alter_actionimpactcheck_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailybrief',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='dailybrief',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='briefaction',
            name='discount_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='briefaction',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='briefaction',
            name='action_type',
            field=models.CharField(choices=[('discount', 'Discount'), ('review_menu', 'Review menu')], max_length=20),
        ),
    ]
