# Generated by Django 6.1 on 2026-08-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0006_alter_dailybrief_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefaction',
            name='discount_ingredient_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
