# Generated by Django 6.1 on 2026-08-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0007_briefaction_discount_ingredient_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefaction',
            name='reasoning',
            field=models.TextField(blank=True, default=''),
        ),
    ]
